# Generated by Django 5.2 on 2025-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0003_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
