# Generated by Django 5.2 on 2025-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0010_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_meterial',
            field=models.FileField(default=1, upload_to='course_meterial/'),
            preserve_default=False,
        ),
    ]
