# Generated by Django 5.2 on 2025-07-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0013_coursevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Courses_app.course'),
        ),
    ]
