# Generated by Django 5.2 on 2025-06-15 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0009_alter_enrollment_course'),
        ('Payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses_app.enrollment'),
            preserve_default=False,
        ),
    ]
