# Generated by Django 5.2 on 2025-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_app', '0002_remove_payment_course_payment_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='amount',
        ),
    ]
