# Generated by Django 5.2 on 2025-06-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0011_course_course_meterial'),
        ('Payment_app', '0003_rename_payment_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses_app.course'),
            preserve_default=False,
        ),
    ]
