# Generated by Django 5.2 on 2025-06-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_app', '0011_course_course_meterial'),
        ('Payment_app', '0004_payment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses_app.course'),
        ),
    ]
