# Generated by Django 5.2 on 2025-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
