# Generated by Django 5.2 on 2025-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
